version: '3.9'

services:
  app:
    container_name: chaos-mano_app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JWT_SECRET=${JWT_SECRET:-supersecretcode}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-604800}
      - MONGO_URI=${MONGO_URI}
    ports:
      - '${APP_PORT:-8080}:8080'
    networks:
      - network

networks:
  network:
    driver: bridge
